apiVersion: v1
kind: Service
metadata:
  name: cogapi
spec:
  ports:
    - name: api
      port: 80
      targetPort: 4000
    - name: trigger
      port: 4001
      targetPort: 4001
    - name: service
      port: 4002
      targetPort: 4002
  selector:
    app: cog
    tier: frontend
  type: LoadBalancer
